# Generated by Django 4.2.7 on 2023-12-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_post_updated_at_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='notice/files/%Y/%m/%d/'),
        ),
    ]
