# Generated by Django 4.2.7 on 2023-12-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_post_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='blog/images/%Y/%m/%d/'),
        ),
    ]
